### ISSUE TITLE
Feedback liken

### ISSUE THREAD

**Issue by slimluccii** [Stefan-Espant/hallo-strandeiland#40]
## Top

Toffe animatie voor het liken.

## Tip

Ik weet als gebruiker niet wat de geliked state is van tevoren. Ik zou denken wanneer ik een gevuld hartje zie dat ik hem al geliked heb. Misschien wil je een outlined hartje laten zien.

**Comment by Stefan-Espant** [comment]
Bedankt voor je feedback, het is verwerkt in het Figma ontwerp
