### ISSUE TITLE
design critique

### ISSUE THREAD

**Issue by r20222** [Stefan-Espant/hallo-strandeiland#41]
top: ik vind het een mooi design met duidelijke wensvlakken met border 👍 
tip: de zoekbalk kan misschien duidelijker, waar zoek je precies op? Misschien voor de toegankelijkheid 'menu' tekst onder het hamburger menu?

**Comment by Stefan-Espant** [comment]
Bedankt voor je feedback, we hebben het verwerkt in het Figma ontwerp. De tekst menu staat rechts van het icoon momenteel.
